services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/workspace
    env_file:
      - ./backend/.env
    environment:
      - ENV_VAR_EXAMPLE=value

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
